export default interface IEvolutionChain{
    id:number,
    chain:{
        evolves_to:{
            species?:{
                name?:string,
                url?:string
            },
            evolves_to:{
                species:{
                    name?:string
                    url?:string
                }
            }[]
        }[],
        species:{
            name?:string,
            url?:string
        },
    }
}